"""
ipf_endo_analysis.py — IPF vs endometriosis research comparison.

Reads annual publication counts from data/publication_counts.csv (generated by
fetch_data.py) and plots side-by-side trend lines to illustrate the research
volume disparity between IPF and endometriosis.

Data source: PubMed E-utilities API via fetch_data.py
Search terms established: March 2026
  - endo_all:     'endometriosis'
  - endo_genetic: 'endometriosis AND (genes OR genetic)'
  - ipf_all:      'idiopathic pulmonary fibrosis'
  - ipf_genetic:  'idiopathic pulmonary fibrosis AND (genes OR genetic)'

Cumulative totals (1930–2026, as of March 2026 fetch):
  - All Endometriosis Studies:        43,755
  - Genetic Mechanisms Endometriosis:  6,815
  - All IPF Studies:                  20,742
  - Genetic Mechanisms IPF:            4,599
"""

from pathlib import Path

import pandas as pd
import matplotlib.pyplot as plt

DATA_FILE = Path(__file__).parent / "data" / "publication_counts.csv"


def main():
    df = pd.read_csv(DATA_FILE)

    fig, ax = plt.subplots(figsize=(14, 8))

    ax.plot(df["year"], df["endo_all"],     label="All Endometriosis Studies",
            color="blue",  linewidth=2)
    ax.plot(df["year"], df["endo_genetic"], label="Genetic Mechanisms of Endometriosis",
            color="blue",  linewidth=1.5, linestyle="--")
    ax.plot(df["year"], df["ipf_all"],      label="All IPF Studies",
            color="green", linewidth=2)
    ax.plot(df["year"], df["ipf_genetic"],  label="Genetic Mechanisms of IPF",
            color="green", linewidth=1.5, linestyle="--")

    ax.set_xlabel("Year")
    ax.set_ylabel("Publications per Year")
    ax.set_title("PubMed Articles Related to Endometriosis and IPF (1930–2026)")
    ax.legend()
    ax.grid(True, alpha=0.3)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()


if __name__ == "__main__":
    main()
