"""
pubmed_endometriosis_analysis.py — Publication timeline for endometriosis and IPF.

Reads annual publication counts from data/publication_counts.csv (generated by
fetch_data.py) and plots per-year and cumulative trends for all four categories.

Data source: PubMed E-utilities API via fetch_data.py
Search terms established: March 2026
  - endo_all:     'endometriosis'
  - endo_genetic: 'endometriosis AND (genes OR genetic)'
  - ipf_all:      'idiopathic pulmonary fibrosis'
  - ipf_genetic:  'idiopathic pulmonary fibrosis AND (genes OR genetic)'

Cumulative totals (1930–2024, as of March 2026 fetch):
  - All Endometriosis Studies:        40,289
  - Genetic Mechanisms Endometriosis:  6,127
  - All IPF Studies:                  18,768
  - Genetic Mechanisms IPF:            4,020
"""

from pathlib import Path

import pandas as pd
import matplotlib.pyplot as plt

DATA_FILE = Path(__file__).parent / "data" / "publication_counts.csv"


def add_cumulative_labels(ax, x, y, label_interval=20, color="black"):
    """Annotate the line with running cumulative totals at regular year intervals."""
    cumulative = y.cumsum()
    years = x.values
    first_nonzero = next((i for i, v in enumerate(y.values) if v > 0), 0)
    start_year = years[first_nonzero]

    for year in range(int(start_year), int(years[-1]) + 1, label_interval):
        if year in x.values:
            idx = list(x.values).index(year)
            ax.text(year, y.iloc[idx], f"{cumulative.iloc[idx]:,}",
                    fontsize=8, ha="center", va="bottom", color=color)
    # Always label the final year
    ax.text(years[-1], y.iloc[-1], f"{cumulative.iloc[-1]:,}",
            fontsize=8, ha="center", va="bottom", color=color)


def main():
    df = pd.read_csv(DATA_FILE)

    fig, ax = plt.subplots(figsize=(14, 8))

    ax.plot(df["year"], df["endo_all"],     label="All Endometriosis Studies",
            color="blue",  linewidth=2)
    ax.plot(df["year"], df["endo_genetic"], label="Genetic Mechanisms of Endometriosis",
            color="blue",  linewidth=1.5, linestyle="--")
    ax.plot(df["year"], df["ipf_all"],      label="All IPF Studies",
            color="green", linewidth=2)
    ax.plot(df["year"], df["ipf_genetic"],  label="Genetic Mechanisms of IPF",
            color="green", linewidth=1.5, linestyle="--")

    add_cumulative_labels(ax, df["year"], df["endo_all"],     label_interval=20, color="blue")
    add_cumulative_labels(ax, df["year"], df["endo_genetic"], label_interval=20, color="steelblue")
    add_cumulative_labels(ax, df["year"], df["ipf_all"],      label_interval=20, color="green")
    add_cumulative_labels(ax, df["year"], df["ipf_genetic"],  label_interval=20, color="darkgreen")

    ax.set_xlabel("Year")
    ax.set_ylabel("Publications per Year")
    ax.set_title("PubMed Articles Related to Endometriosis and IPF (1930–2024)")
    ax.legend()
    ax.grid(True, alpha=0.3)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()


if __name__ == "__main__":
    main()
